fix: find python executable for color generation
The color generation script searches for python in PATH using common
names for the executable

diff --git a/run_before_00-generate-colors.sh.tmpl b/run_before_00-generate-colors.sh.tmpl
--- a/run_before_00-generate-colors.sh.tmpl
+++ b/run_before_00-generate-colors.sh.tmpl
@@ -1,8 +1,20 @@
 #!/usr/bin/env sh
 
+python=""
+if command -v python3 > /dev/null; then
+    python=python3
+elif command -v python2 > /dev/null; then
+    python=python2
+elif command -v python > /dev/null; then
+    python=python
+else
+    echo "Could not find a python in PATH" >&2
+    exit 1
+fi
+
 colorscheme={{ .colorscheme | quote }}
 color_dir="{{ .chezmoi.sourceDir }}/_color"
 script="$color_dir/color.py"
 color_file="$color_dir/color.json"
 
-python3 "$script" "$colorscheme" > "$color_file"
+"$python" "$script" "$colorscheme" > "$color_file"
