style: change indent to 2

diff --git a/dot_local/bin/executable_dims b/dot_local/bin/executable_dims
--- a/dot_local/bin/executable_dims
+++ b/dot_local/bin/executable_dims
@@ -9,20 +9,20 @@
 quick=0
 
 if [ $# -ge 1 ]; then
-    case "$1" in
-        -q | --quick) quick=1 ;;
-        *)
-            echo "Invalid input" >&2
-            return 1
-            ;;
-    esac
+  case "$1" in
+    -q | --quick) quick=1 ;;
+    *)
+      echo "Invalid input" >&2
+      return 1
+      ;;
+  esac
 fi
 
 if [ $quick -eq 1 ]; then
-    printf "\r%d × %d " $(tput cols) $(tput lines)
+  printf "\r%d × %d " $(tput cols) $(tput lines)
 else
-    while true; do
-        printf "\r%d × %d " $(tput cols) $(tput lines)
-        sleep 0.1
-    done
+  while true; do
+    printf "\r%d × %d " $(tput cols) $(tput lines)
+    sleep 0.1
+  done
 fi
diff --git a/run_before_10-generate-colors.sh.tmpl b/run_before_10-generate-colors.sh.tmpl
--- a/run_before_10-generate-colors.sh.tmpl
+++ b/run_before_10-generate-colors.sh.tmpl
@@ -2,14 +2,14 @@
 
 python=""
 if command -v python3 > /dev/null; then
-    python=python3
+  python=python3
 elif command -v python2 > /dev/null; then
-    python=python2
+  python=python2
 elif command -v python > /dev/null; then
-    python=python
+  python=python
 else
-    echo "Could not find a python in PATH" >&2
-    exit 1
+  echo "Could not find a python in PATH" >&2
+  exit 1
 fi
 
 colorscheme={{ .colorscheme | quote }}
