style: change indent to 2

diff --git a/dot_local/bin/executable_nightshift b/dot_local/bin/executable_nightshift
--- a/dot_local/bin/executable_nightshift
+++ b/dot_local/bin/executable_nightshift
@@ -19,20 +19,20 @@
 temperature=""
 
 if [ $# -ge 1 ]; then
-    case "$1" in
-        o | off)      temperature="" ;;
-        d | dusk )    temperature="5500K" ;;
-        n | night)    temperature="4500K" ;;
-        w | witching) temperature="3500K" ;;
-        *)
-            echo "Invalid input" >&2
-            return 1
-            ;;
-    esac
+  case "$1" in
+    o | off)      temperature="" ;;
+    d | dusk )    temperature="5500K" ;;
+    n | night)    temperature="4500K" ;;
+    w | witching) temperature="3500K" ;;
+    *)
+      echo "Invalid input" >&2
+      return 1
+      ;;
+  esac
 fi
 
 # Always clear the screen since the temperature changes stack multiplicatively
 redshift -x > /dev/null
 if [ ! -z "$temperature" ]; then
-    redshift -O $temperature > /dev/null
+  redshift -O $temperature > /dev/null
 fi
